spring.application.name=kitch
spring.datasource.url=jdbc:h2:file:./kitch-db;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
kitch.seed-data=true
server.port=8080
